---
- hosts: control
  become: true
  tasks:
    - name: using with_items
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - python-pip
        - nginx
        - mysql-server
        - python-virtualenv

    - name: ensure nginx started
      service: name=nginx state=started enabled=yes
      notify: restart nginx

    - name: copy demo app source
      copy: src:demo/app dest=/var/www/demo mode=0755
      notify: restart nginx

    #lineinfile
    - name: using linein file
      lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
                  line="bind-address = 0.0.0.0"

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
